AYUDAS = {
 "hueso": "The first digit of the code. Since 2018 the paired bones are coded separately: radius 2R, ulna 2U, fibula 4F.",
 "segmento": "It determines what the letter that follows will mean.",
 "identificador": "The compendium leaves a gap between dots for the number of the ray, digit, rib or vertebra.",
 "tipo": "The letter. It means different things depending on the segment: in the shaft it speaks of fragmentation, in an end segment of articular involvement, in the scapula of location.",
 "grupo": "The number after the letter.",
 "subgrupo": "The final decimal. Maximum detail; interobserver agreement falls a great deal at this level.",
 "calificaciones": "Lower-case letters in brackets, particular to this fracture. Optional and cumulative.",
 "modificadores": "In square brackets at the end. They apply to almost any fracture and are optional.",
 "cl-schatzker": "It is the language in which the plateau is discussed and it points to the implant: types I-III are lateral, type IV is medial and carries a different prognosis, and V-VI separate the block from the shaft. Kfuri's modification completes the type with the quadrant involved, which is what Schatzker alone does not say: that is why the two questions go together.",
 "cl-columnas": "This is the second half of the classification and the one that really decides the approach and the position. Kfuri divides the plateau into quadrants with two lines and forces you to name the quadrant, which is the information the Schatzker type does not contain.",
 "cl-garden": "It separates fixing from replacing, which is the most important decision in this fracture.",
 "cl-pauwels": "It is the only classification on this list that speaks directly of biomechanics: the more vertical the line, the more shear and the less compression. It connects with Step 5.",
 "cl-neer": "It is the universal vocabulary of the proximal humerus and sets the classic displacement thresholds: 1 cm or 45 degrees.",
 "cl-hertel": "It predicts head ischaemia better than the number of parts, and therefore guides the choice between fixing and replacing. Mark those that are present.",
 "cl-hawkins": "It predicts avascular necrosis of the body, which is what determines the result of this fracture.",
 "cl-sanders": "It is defined on coronal CT of the posterior facet and it determines the prognosis and the indication: type IV leads you to consider primary subtalar arthrodesis.",
 "cl-letournel": "It decides the approach, and in the acetabulum the approach is the operation. There is no alternative to naming the pattern.",
 "cl-young-burgess": "It classifies by mechanism and therefore anticipates the bleeding pattern and the associated injuries. It is the one that connects with Step 1: it changes the resuscitation, not only the fixation.",
 "cl-tile": "It classifies by stability, which is what decides whether posterior fixation is needed. It complements Young and Burgess: one gives the mechanism, the other the stability.",
 "cl-vancouver": "It is the classification on this list that decides most: it separates fixing from revising the stem, which are two different operations with two different teams.",
 "cl-winquist": "It measures how much cortex is left to share load, and with it whether the nail can be dynamised or has to stay static.",
 "cl-mason": "It separates what is treated functionally from what is fixed and from what is replaced. Type IV obliges you to look for the associated ligament injury.",
 "cl-lauge-hansen": "It classifies by mechanism, and the mechanism is undone in reverse: it is the one that tells you the reduction manoeuvre. It connects with Step 9.",
}

CRITERIOS = {
 "Abordaje posterolateral, con osteotomía del peroné o ventana posterior según el caso": "Posterolateral approach, with a fibular osteotomy or a posterior window depending on the case",
 "Aumenta el volumen pélvico: faja o fijador externo urgente": "It increases the pelvic volume: urgent binder or external fixator",
 "Añade fractura en asa de cubo del ala ilíaca": "It adds a bucket-handle fracture of the iliac wing",
 "Bloqueo estático obligado": "Static locking is mandatory",
 "Buen candidato a reducción y osteosíntesis": "A good candidate for reduction and internal fixation",
 "Busca la tríada terrible: coronoides y ligamento colateral lateral": "Look for the terrible triad: coronoid and lateral collateral ligament",
 "Cabeza, una tuberosidad y diáfisis": "Head, one tuberosity and shaft",
 "Clavo o placa según hueso y desplazamiento": "Nail or plate according to the bone and the displacement",
 "Componente mixto de compresión y cizallamiento": "A mixed component of compression and shear",
 "Compresión lateral de un lado y apertura del contrario": "Lateral compression on one side and opening on the other",
 "Comprueba el bloqueo mecánico bajo anestesia": "Check for mechanical block under anaesthesia",
 "Conminución de la faceta posterior": "Comminution of the posterior facet",
 "Contacto suficiente para tolerar dinamización": "Enough contact to tolerate dynamisation",
 "Cuerpo extruido: reducción urgente, y vigilar la piel": "The body is extruded: urgent reduction, and watch the skin",
 "Cuidado con la zona entre implantes: solapa la placa con el vástago": "Beware of the zone between implants: overlap the plate with the stem",
 "Cuña lateral sin hundimiento": "A lateral wedge with no depression",
 "De las más difíciles: casi siempre dos ventanas": "One of the hardest: almost always two windows",
 "Desplazamiento craneal de la hemipelvis": "Cranial displacement of the hemipelvis",
 "Disociación completa de la hemipelvis": "Complete dissociation of the hemipelvis",
 "Disrupción completa del complejo posterior": "Complete disruption of the posterior complex",
 "Diástasis del pubis menor de 2,5 cm": "Pubic diastasis under 2.5 cm",
 "Diástasis mayor de 2,5 cm con sacroilíacos anteriores rotos": "Diastasis over 2.5 cm with the anterior sacroiliac ligaments torn",
 "Dos trazos, con un fragmento central hundido": "Two fracture lines, with a depressed central fragment",
 "El bloque articular queda separado de la diáfisis: son dos zonas": "The articular block is separated from the shaft: that is two zones",
 "El clavo soporta toda la carga": "The nail carries the whole load",
 "El cuadrante clásico de la separación-hundimiento lateral": "The classic quadrant of the lateral split-depression",
 "El de acceso más difícil: queda por detrás del peroné y por debajo del ciático poplíteo externo": "The hardest to reach: it lies behind the fibula and below the common peroneal nerve",
 "El patrón más frecuente": "The commonest pattern",
 "El patrón que mejor concordancia tiene": "The pattern with the best agreement",
 "El patrón que más sangra y más transfunde": "The pattern that bleeds and transfuses most",
 "El platillo medial es el que soporta más carga: peor pronóstico": "The medial plateau carries most of the load: worse prognosis",
 "El signo del espolón en la proyección obturatriz lo confirma": "The spur sign on the obturator oblique confirms it",
 "Elevación por ventana metafisaria y relleno": "Elevation through a metaphyseal window and grafting",
 "En el mayor de 65 años la respuesta suele ser artroplastia, no fijación": "In the patient over 65 the answer is usually arthroplasty, not fixation",
 "Es el fragmento que más se olvida y el que más falla": "It is the fragment most often forgotten and the one that most often fails",
 "Es el predictor más fuerte de isquemia": "It is the strongest predictor of ischaemia",
 "Estable; el mecanismo cierra el anillo": "Stable; the mechanism closes the ring",
 "Exige contrafuerte posteromedial por su propio abordaje": "It demands a posteromedial buttress through its own approach",
 "Exige elevar el hundimiento y rellenar el defecto": "It demands elevating the depression and filling the defect",
 "Exige fijación posterior: tornillos iliosacros o placa": "It demands posterior fixation: iliosacral screws or a plate",
 "Fijación con tornillos si bloquea la rotación": "Screw fixation if it blocks rotation",
 "Fijación in situ con tornillos o tornillo deslizante": "In situ fixation with screws or a sliding hip screw",
 "Fractura de ramas más impactación del sacro": "Rami fracture plus sacral impaction",
 "Habitualmente por vía anterior, con control indirecto de la posterior": "Usually through an anterior route, with indirect control of the posterior one",
 "Hundimiento o separación de la mitad anterior del platillo medial": "Depression or split of the anterior half of the medial plateau",
 "Hundimiento puro que la radiografía de frente no enseña: exige TC": "A pure depression the AP radiograph does not show: it needs CT",
 "Ilioinguinal o anterior intrapélvico": "Ilioinguinal or anterior intrapelvic",
 "Ilioinguinal o anterior intrapélvico, en supino": "Ilioinguinal or anterior intrapelvic, supine",
 "Impactación": "Impaction",
 "Impactada en valgo o completa sin desplazar": "Valgus impacted or complete without displacement",
 "Inestabilidad vertical: la faja no la controla": "Vertical instability: a binder does not control it",
 "Kocher-Langenbeck; comprueba el ciático desde el principio": "Kocher-Langenbeck; check the sciatic nerve from the start",
 "La cabeza está fuera de la glena: urgencia relativa": "The head is out of the glenoid: a relative emergency",
 "La cabeza probablemente conserva vascularización: la fijación es razonable": "The head probably retains its blood supply: fixation is reasonable",
 "La cabeza radial es un estabilizador secundario que aquí pasa a primario": "The radial head is a secondary stabiliser that here becomes primary",
 "La más frecuente": "The commonest",
 "La operación es revisar el vástago, no fijar la fractura": "The operation is to revise the stem, not to fix the fracture",
 "La placa lateral NO lo controla": "The lateral plate does NOT control it",
 "La resección aislada está contraindicada si hay inestabilidad": "Isolated excision is contraindicated if there is instability",
 "Las dos mesetas, con la diáfisis todavía en continuidad": "Both plateaus, with the shaft still in continuity",
 "Lesión del cartílago articular (escala ICRS)": "Articular cartilage injury (ICRS scale)",
 "Libro abierto o compresión lateral": "Open book or lateral compression",
 "Lleva identificador: se completa en el paso siguiente.": "It carries an identifier: completed in the next step.",
 "Longitud y rotación dependen por completo de los pernos": "Length and rotation depend entirely on the bolts",
 "Los tornillos paralelos trabajan a cizallamiento y ceden": "Parallel screws then work in shear and give way",
 "Luxación": "Dislocation",
 "Menos de 2 mm, cualquiera que sea el número de trazos": "Under 2 mm, whatever the number of fracture lines",
 "Menos del 25 % de la circunferencia": "Less than 25% of the circumference",
 "Movilización precoz": "Early mobilisation",
 "Necrosis prácticamente segura": "Necrosis is virtually certain",
 "Ningún fragmento articular queda unido al esqueleto axial": "No articular fragment stays attached to the axial skeleton",
 "Ningún fragmento supera 1 cm o 45°": "No fragment exceeds 1 cm or 45°",
 "No reconstruible: valorar prótesis de cabeza radial": "Not reconstructable: consider a radial head replacement",
 "Ojo: muchas «no desplazadas» tienen rotación en la TC": "Careful: many «undisplaced» ones show rotation on CT",
 "Osteosíntesis con placa bloqueada, cables o combinación": "Fixation with a locked plate, cables or a combination",
 "Patrones mixtos, habitualmente por caída de altura": "Mixed patterns, usually from a fall from height",
 "Patrón asociado más frecuente": "The commonest associated pattern",
 "Peor pronóstico funcional: valorar artrodesis subastragalina primaria": "Worse functional prognosis: consider primary subtalar arthrodesis",
 "Peroné alto: descarta una Maisonneuve palpando todo el peroné": "High fibula: rule out a Maisonneuve by palpating the whole fibula",
 "Peroné conminuto lateral, por encima de la sindesmosis": "Comminuted lateral fibula, above the syndesmosis",
 "Pide ángulo fijo, o añadir un tornillo antirrotatorio o una placa de sostén": "It calls for a fixed angle, or adding an antirotation screw or a buttress plate",
 "Poner una placa sobre un vástago suelto es fallo garantizado": "Putting a plate over a loose stem is guaranteed failure",
 "Puede ser una luxación de rodilla reducida: descarta lesión del peroneo y vascular": "It may be a reduced knee dislocation: exclude peroneal nerve and vascular injury",
 "Reducción: pronar y abducir": "Reduction: pronate and abduct",
 "Reducción: rotación interna, que es el gesto contrario al del mecanismo": "Reduction: internal rotation, the opposite of the injuring mechanism",
 "Revisión con vástago largo, aloinjerto o megaprótesis": "Revision with a long stem, allograft or megaprosthesis",
 "Riesgo alto de necrosis de la cabeza": "High risk of head necrosis",
 "Riesgo alto de necrosis y de no unión": "High risk of necrosis and non-union",
 "Riesgo del 20 al 50 %": "Risk of 20 to 50%",
 "Riesgo por encima del 80 %": "Risk above 80%",
 "Se alcanza por el abordaje lateral, con el paciente en supino": "Reached through the lateral approach, with the patient supine",
 "Se alcanza por el abordaje medial; la placa lateral no lo sostiene": "Reached through the medial approach; the lateral plate does not hold it",
 "Se luxa en flexión: la placa lateral y la anteromedial no lo controlan": "It subluxes in flexion: neither the lateral nor the anteromedial plate controls it",
 "Se mide en el calcar, sobre el fragmento cefálico": "It is measured at the calcar, on the head fragment",
 "Se trata como una fractura de fémur distal": "It is treated as a distal femoral fracture",
 "Secciona el aporte cefálico por debajo del cuello anatómico": "It cuts the supply to the head below the anatomical neck",
 "Separa el acetábulo en mitad superior e inferior": "It separates the acetabulum into upper and lower halves",
 "Sin bisagra medial no hay aporte por la arteria circunfleja anterior": "Without a medial hinge there is no supply from the anterior circumflex artery",
 "Sin trazo de separación: la ligamentotaxis no lo levanta": "No split line: ligamentotaxis does not lift it",
 "Situación mecánicamente favorable": "A mechanically favourable situation",
 "Subluxación / inestabilidad ligamentosa": "Subluxation / ligamentous instability",
 "Suele bastar con fijación anterior": "Anterior fixation is usually enough",
 "Todavía comparte carga": "It still shares load",
 "Tornillos percutáneos si no hay desplazamiento": "Percutaneous screws if there is no displacement",
 "Trabéculas rotas o discontinuas": "Trabeculae broken or discontinuous",
 "Tracción excéntrica del manguito: escenario de banda de tensión": "Eccentric pull of the cuff: a tension band setting",
 "Transversa más trazo vertical": "Transverse plus a vertical line",
 "Trazo casi horizontal: la carga comprime el foco": "An almost horizontal line: the load compresses the fracture",
 "Trazo casi vertical: la carga cizalla en vez de comprimir": "An almost vertical line: the load shears instead of compressing",
 "Trazo espiroideo del peroné a la altura de la sindesmosis": "Spiral fibular line at the level of the syndesmosis",
 "Trazo transverso del maléolo medial por avulsión": "Transverse avulsion line of the medial malleolus",
 "Trazo transverso del peroné por debajo de la sindesmosis": "Transverse fibular line below the syndesmosis",
 "Trazo vertical del maléolo medial: pide contrafuerte, no tornillos a fricción": "Vertical line of the medial malleolus: it calls for a buttress, not friction screws",
 "Trocánter mayor o menor": "Greater or lesser trochanter",
 "Umbral quirúrgico más bajo en el paciente activo, sobre 5 mm": "A lower surgical threshold in the active patient, around 5 mm",
 "Un trazo en la faceta posterior": "One fracture line in the posterior facet",
 "Valorar artroplastia invertida en el mayor": "Consider reverse arthroplasty in the older patient",
 "Ya no hay columna que comparta carga": "There is no column left to share load",
}

# Nombres de dedo o radio del identificador. Solo dos difieren en inglés;
# el resto (Pulgar→Thumb, etc.) ya coincide o es número.
IDENTIFICADORES = {
    "Índice (2)": "Index (2)",
    "Meñique (5)": "Little (5)",
}

# Nombre de cada clasificación regional, para regenerar el derivado «regionales»
# en inglés exactamente como lo hace build_clasificaciones.py en español.
NOMBRES = {
    "Schatzker modificada por Kfuri": "Schatzker as modified by Kfuri",
    "Schatzker modificada por Kfuri · columnas": "Schatzker as modified by Kfuri · quadrants",
    "Garden": "Garden",
    "Pauwels": "Pauwels",
    "Neer": "Neer",
    "Hertel · predictores de isquemia": "Hertel · predictors of ischaemia",
    "Hawkins": "Hawkins",
    "Sanders": "Sanders",
    "Letournel y Judet": "Letournel and Judet",
    "Young y Burgess": "Young and Burgess",
    "Tile · AO pelvis": "Tile · AO pelvis",
    "Vancouver": "Vancouver",
    "Winquist y Hansen": "Winquist and Hansen",
    "Mason": "Mason",
    "Lauge-Hansen": "Lauge-Hansen",
}
DERIVADOS_TITULOS = {
    "codigo": "AO/OTA 2018 code",
    "oficial": "Official description from the compendium",
    "regionales": "What the regional classification adds",
}
NOTA_CODIGO = ("No hyphen: the 2018 revision removed it. Order: bone · location · "
               "type · group · subgroup · (qualifications) · [modifiers].")
